config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :ships, only: [:index, :show, :new, :create, :update] do
    resources :bookings, only: [:create]
  end

  resources :bookings, only: [:update, :index ]
  get 'my_ships', to: 'ships#user_index'

  namespace :owner do
    resources :bookings, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :ship
  validates :start_date, presence: true
  validates :end_date, presence: true

  # validates :end_date, comparison: { greater_than: :start_date, message: "must follow start date." }
  # validates :start_date, comparison: { greater_than: Date.today, message: "must be today or later." }
  def pending?
    status == 'pending'
  end
end

app/models/ship.rb
class Ship < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many_attached :photos
  validates :description, length: { minimum: 10 }
  validates :capacity, numericality: { greater_than: 0 }
  validates :price_per_day, numericality: { greater_than: 0 }

  include PgSearch::Model
  pg_search_scope :global_search,
    against: {
      name: 'A',
      description: 'B'
    },
    using: {
      tsearch: { prefix: true }
    }

  scope :by_max_price, ->(max_price) { where('price_per_day <= ?', max_price) }
  scope :by_min_rating, ->(min_rating) { where('rating >= ?', min_rating) }
  scope :by_min_capacity, ->(min_capacity) { where('capacity >= ?', min_capacity) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :ships
  has_many :bookings
  has_many :bookings_as_owner, through: :ships, source: :bookings
  has_one_attached :user_img
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @user = current_user
    @today = Date.today
    @bookings = current_user.bookings_as_owner
  end

  def create
    @ship = Ship.find(params[:ship_id])
    @booking = Booking.new(booking_params)
    @booking.status = "pending"
    @booking.ship = @ship
    @booking.user = current_user
    @booking.rating_done = "F"
    if @booking.save
      redirect_to bookings_path
    else
      render "ships/show", status: :unprocessable_entity
    end
  end

  def update
    @booking = Booking.find(params[:id])

    if @booking.status != "pending" && @booking.rating_done == "F"
      @booking.ship.rating_count += 1
      @booking.ship.rating = (params[:booking][:rating_booking].to_f +  @booking.ship.rating)/@booking.ship.rating_count
      @booking.rating_done = "Y"
    end
    if @booking.update(booking_params)
      redirect_to bookings_path
    else
      render "bookings", status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status, :rating_booking, :rating_comment)
  end
end

app/controllers/owner/bookings_controller.rb
class Owner::BookingsController < ApplicationController
  # before_action :authenticate_user!
  def index
    # @user = current_user
    @bookings = current_user.bookings_as_owner
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @ships = Ship.all
  end
end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @ships = Ship.all
    if params[:q].present?
      @ships = @ships.global_search(params[:q])
    end

    if params[:max_price].present?
      @ships = @ships.where('price_per_day <= ?', params[:max_price].to_i)
    end

    if params[:min_rating].present?
      @ships = @ships.where('rating >= ?', params[:min_rating].to_f)
    end

    if params[:min_capacity].present?
      @ships = @ships.where('capacity >= ?', params[:min_capacity].to_i)
    end

    # If no search parameters are provided, show all ships
    if !params[:q].present? && !params[:max_price].present? && !params[:min_rating].present? && !params[:min_capacity].present?
      @ships = Ship.all
    end
  end

  def show
    @hello = "hello"
    @ship = Ship.find(params[:id])
    @booking = Booking.new
  end

  def user_index
    # if current_user.nil?
    #   redirect_to ships_path
    # else
    # @ships = Ship.where(user_id: current_user.id)
    @user = User.find(current_user.id)
    @ships = Ship.where(user_id: @user)
    # end
  end

  def new
    @ship = Ship.new
  end

  def create
    @ship = Ship.new(ship_params)
    @ship.user_id = current_user.id
    @ship.rating_count = 0
    @ship.rating = 0.0
    if @ship.save
      redirect_to ship_path(@ship.id)
    else
      # raise
      render :new, status: :unprocessable_entity
    end
  end

  private

  def ship_params
    params.require(:ship).permit(:name, :description, :capacity, :price_per_day, :rating, :body, photos: [])
  end

end

app/controllers/spaceships_controller.rb
class SpaceshipsController < ApplicationController

  def index
    @ships = Ship.all
  end

  def show
    @ship = Ship.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_dib.html.erb
<div class="card-trip">
  <%= image_tag(booking.ship.picture_1) %>
  <div class="card-trip-infos">
      <h2 class="mb-2"><%= booking.ship.name%></h2>
      <p class="mb-3"><%= booking.ship.description %></p>
        <div class="booking-date align-self-end">
          <p><strong>Booking dates: </strong><%= booking.start_date %> - <%= booking.end_date %></p>
        </div>
        <% if booking.end_date < @today && booking.rating_done == "F" %>
          <%= simple_form_for booking do |f| %>
            <%#= f.input :rating, as: :radio_buttons, collection: [['0', '0'], ['1', 'male']], label_method: :second, value_method: :first %>
            <%=  f.input :rating_booking, collection: 0..5, prompt: "Please rate your experience", selected: 5 %>
            <%=  f.input :rating_comment, class: "bg-light", default: "Please rate your experience" %>
            <%= f.submit 'Rate', class: 'btn btn-info' %>
          <% end %>
        <% end %>
  </div>
</div>

app/views/bookings/_dibs.html.erb
<div class="container">
<h1 class="mt-4">My Dibs</h1>
  <div class="cards mt-4">
    <% @bookings.each do |booking| %>
    <div class="card-trip">
      <%= image_tag "spaceship2.jpeg" %>
      <div class="card-content">
          <h2>Ship name here</h2>
          <p>Description here?</p>
          <p><%= booking.start_date %> - <%= booking.end_date %></p>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/bookings/_form.html.erb
<h1>Book yours</h1>
<%= simple_form_for [@ship, @booking] do |f| %>
  <%= f.input :start_date, as: :date, html5: true %>
  <%= f.input :end_date, as: :date, html5: true %>
  <%= f.button :submit , class: "btn btn-light"%>
<% end %>

app/views/bookings/_ship.html.erb
<div class="card-trip">
  <%= image_tag(ship.picture_1) %>
  <div class="card-trip-infos">
      <h2 class="mb-2"><%= ship.name %></h2>
      <p class="mb-3"><%= ship.description %></p>
  </div>
</div>

app/views/bookings/index.html.erb
<ul class="nav tabs-underlined" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <span class="nav-link tab-underlined active" id="bookings-tab" data-bs-toggle="tab" data-bs-target="#bookings-tab-pane" role="tab" aria-controls="bookings-tab-pane" aria-selected="true">Bookings</span>
  </li>
  <li class="nav-item" role="presentation">
    <span class="nav-link tab-underlined" id="requests-tab" data-bs-toggle="tab" data-bs-target="#requests-tab-pane" role="tab" aria-controls="requests-tab-pane" aria-selected="false">Requests</span>
  </li>
  <li class="nav-item" role="presentation">
    <span class="nav-link tab-underlined" id="listings-tab" data-bs-toggle="tab" data-bs-target="#listings-tab-pane" role="tab" aria-controls="listings-tab-pane" aria-selected="false">Listings</span>
  </li>
</ul>

<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade py-3 show active" id="bookings-tab-pane" role="tabpanel" aria-labelledby="bookings-tab" tabindex="0">
    <div class="container my-5">
      <h1 class="show-page-header">My Bookings</h1>
      <div class="cards">
        <% if user_signed_in? %>
            <% @user.bookings.each do |booking| %>
              <%= render 'bookings/dib', booking: booking %>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="tab-pane fade py-3" id="requests-tab-pane" role="tabpanel" aria-labelledby="requests-tab" tabindex="0">
    <div class="container my-5">
      <h1 class="show-page-header">My Requests</h1>
      <div class="cards">
        <% if user_signed_in? %>
            <% @bookings.each do |booking| %>
              <%= render 'owner/bookings/owner_bookings', booking: booking %>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="tab-pane fade py-3" id="listings-tab-pane" role="tabpanel" aria-labelledby="listings-tab" tabindex="0">
    <div class="container my-5">
      <h1 class="show-page-header">My Listings</h1>
      <div class="cards">
        <% if user_signed_in? %>
            <% @user.ships.each do |ship| %>
              <%= render 'bookings/ship', ship: ship %>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_banner.erb
<div class="banner">
  <section class="space">
    <div class="stars">
      <div class="stars-back"></div>
      <div class="stars-middle"></div>
      <div class="stars-front"></div>
    </div>
    <div class="rocket">
      <div class="fuselage">
        <div class="nose"></div>
        <div class="head">
          <span class="window"></span>
        </div>
        <div class="neck"></div>
        <div class="body"></div>
        <div class="reactor"></div>
        <div class="fire">
          <div class="spark1"></div>
          <div class="spark2"></div>
          <div class="spark3"></div>
          <div class="spark4"></div>
          <div class="spark5"></div>
          <div class="spark6"></div>
        </div>
      </div>
      <div class="left-fin"></div>
      <div class="left-fin-end"></div>
      <div class="right-fin"></div>
      <div class="right-fin-end"></div>
    </div>
  </section>
  <div class="content-overlay">
    <div class="container-banner">
      <h1>Infinity Fleet Rentals</h1>
      <p>Your Odyssey Among the Stars Begins Here!</p>
      <div class="search">
        <%= form_with url: ships_path, method: :get, class: "search" do %>
          <div class="search-bar-container">
            <%= text_field_tag :q,
        params[:q],
        class: "form-control rounded-start",
        placeholder: "Deathstar..."
    %>
            <%= number_field_tag :max_price,
        params[:max_price],
        class: "form-control",
        placeholder: "Max Price",
        min: 0
    %>
            <%= select_tag :min_rating,
        options_for_select((1..5).map { |n| [("★" * n + "☆" * (5 - n)).html_safe, n] }, params[:min_rating]),
        class: "form-control",
        prompt: "Min Rating"
    %>
            <%= number_field_tag :min_capacity,
        params[:min_capacity],
        class: "form-control rounded-end",
        placeholder: "Min Capacity",
        min: 0
    %>
          </div>
          <%= submit_tag "Search", class: 'btn btn-flat'  %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_banner.html.erb
<div class="banner">
  <section class="space">
    <div class="stars">
      <div class="stars-back"></div>
      <div class="stars-middle"></div>
      <div class="stars-front"></div>
    </div>
    <div class="rocket">
      <div class="fuselage">
        <div class="nose"></div>
        <div class="head">
          <span class="window"></span>
        </div>
        <div class="neck"></div>
        <div class="body"></div>
        <div class="reactor"></div>
        <div class="fire">
          <div class="spark1"></div>
          <div class="spark2"></div>
          <div class="spark3"></div>
          <div class="spark4"></div>
          <div class="spark5"></div>
          <div class="spark6"></div>
        </div>
      </div>
      <div class="left-fin"></div>
      <div class="left-fin-end"></div>
      <div class="right-fin"></div>
      <div class="right-fin-end"></div>
    </div>
  </section>
  <div class="content-overlay">
    <div class="container-banner">
      <h1>Infinity Fleet Rentals</h1>
      <p>Your Odyssey Among the Stars Begins Here!</p>
    </div>
  </div>
</div>

app/views/layouts/_search.html.erb
<div class="search">
  <%= form_with url: ships_path, method: :get, class: "search" do %>
    <div class="search-bar-container">
      <%= text_field_tag :q,
        params[:q],
        class: "form-control rounded-start",
        placeholder: "Deathstar..."
    %>
      <%= number_field_tag :max_price,
        params[:max_price],
        class: "form-control",
        placeholder: "Max Price",
        min: 0
    %>
      <div class="d-flex flex-column justify-content-center mx-2 pb-1">
        <div class="star-rating d-flex">
          <input type="radio" name="min_rating" value="1" checked/>
          <input type="radio" name="min_rating" value="2" />
          <input type="radio" name="min_rating" value="3" />
          <input type="radio" name="min_rating" value="4" />
          <input type="radio" name="min_rating" value="5" />
        </div>
      </div>
      <%# <select name="min_rating" id="min_rating" class="form-control" >
        <option value="" disabled="disabled">Min Rating</option>
        <option value="1">★☆☆☆☆</option>
        <option value="2">★★☆☆☆</option>
        <option value="3">★★★☆☆</option>
        <option value="4">★★★★☆</option>
        <option value="5">★★★★★</option></select> %>
      <%= number_field_tag :min_capacity,
        params[:min_capacity],
        class: "form-control rounded-end",
        placeholder: "Min Capa..",
        min: 0
    %>
    </div>
    <div class="d-flex flex-column justify-content-center">
      <%= submit_tag "Search", class: 'btn btn-flat-search m-0'  %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InfinityFleetRentals</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div class="wrapper">
      <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
        <div class="container-fluid">
          <%= link_to root_path, class: 'navbar-brand' do %>
            <%= image_tag "https://res.cloudinary.com/dt99kdrwl/image/upload/v1692250877/production/pngwing.com_nyf6rf.png" %>
          <% end %>
          <%= render 'layouts/search' %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto">
              <li class="nav-item active">
              <%= link_to "See All Ships", ships_path, class: 'nav-link bar' %>
            </li>
            <li class="nav-item">
              <%= link_to "Add a Ship", new_ship_path, class: 'nav-link bar' %>
            </li>
              <% if user_signed_in? %>
                <li class="nav-item dropdown">
                  <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="<%= cl_image_path(current_user.user_img.key) %>"/>
                  <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <%= link_to "View my bookings", bookings_path, class: 'dropdown-item' %>
                    <%= link_to "View my ships", bookings_path, class: 'dropdown-item' %>
                    <a class="dropdown-item" data-turbo-method="delete" href="<%= destroy_user_session_path %>">Log out</a>
                  </div>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "Sign In", new_user_session_path, class: "btn-flat-nav nav-link px-4" %>
                </li>
              <% end %>
              <!--li class="nav-item"-->
              <!--/li-->
            </ul>
          </div>
        </div>
      </div>
      <%= render "shared/flashes" %>
      <%= yield %>
      <div class="footer">
        <div class="footer-links">
          <a href="#"><i class="fab fa-github"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-linkedin"></i></a>
        </div>
        <div class="footer-copyright">
          <i class="fa-regular fa-copyright"></i> Infinity Fleet Rental, inc. All rights reserved.
        </div>
      </div>
    </div>
  </body>
</html>

app/views/owner/bookings/_owner_bookings.html.erb
<div class="card-trip">
  <%= image_tag (booking.ship.picture_1) %>
  <div class="card-trip-infos">
      <h2 class="mb-2"><%= booking.ship.name %></h2>
      <p class="mb-3"><%= booking.ship.description %></p>
    <div class="d-flex">
    <% if booking.pending? %>
      <%= simple_form_for booking do |f| %>
        <%= f.input :status, as: :hidden, input_html: { value: 'accepted'} %>
        <%= f.submit 'Accept', class: 'btn btn-info' %>
      <% end %>
      <%= simple_form_for booking do |f| %>
        <%= f.input :status, as: :hidden, input_html: { value: 'rejected'} %>
        <%= f.submit 'Reject', class: 'btn btn-light' %>
      <% end %>
    <% else %>
      <p class='booking-tag'><strong><%= booking.status.capitalize %></strong></p>
    <% end %>
    </div>
  </div>
</div>

app/views/owner/bookings/index.html.erb
<% @bookings.each do |booking| %>
  <%= render 'owner_bookings', booking: booking %>
<% end %>

<%# could delete if we not showing in different route!! %>
<div class="container my-5">
  <h1 class="show-page-header">My Ships</h1>
    <div class="cards">
      <% if user_signed_in? %>
            <% @bookings.each do |booking| %>
              <%= render 'owner_bookings', booking: booking %>
            <% end %>
        <% end %>
    </div>
</div>

app/views/pages/home.html.erb
 <%= render 'layouts/banner' %>
<div class="subheader-page">
  <h2> Our most popular spaceships</h2>
</div>
<div class="container">
  <div class="cards">
    <% @ships.first(6).each do |ship| %>
      <div class="card-trip">
        <h2 class="card-trip-pricing">$<%=ship.price_per_day.to_i%></h2>
        <%= image_tag ship.picture_1 %>
        <div class="card-trip-infos">
          <div class="card-trip-header">
            <h2><%= ship.name %></h2>
            <div class="d-flex">
              <% ship.rating.round.times do %>
                <i class="fa-solid fa-star"></i>
              <% end %>
              <% (5 - ship.rating.round).times do %>
                <i class="fa-regular fa-star"></i>
              <% end %>
            </div>
          </div>
          <p><%= truncate(ship.description, length:100) %></p>
          <%= link_to "", ship_path(ship), class: 'card-link' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="collapse" id="navbarToggleExternalContent">
  <div class="bg-dark p-4">
    <h5 class="text-white h4">Collapsed content</h5>
    <span class="text-muted">Toggleable via the navbar brand.</span>
  </div>
</div>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>

app/views/ships/_form.html.erb
<%= simple_form_for [@ship, current_user] do |f| %>
  <%= f.input :name, as: :string%>
  <%= f.input :description, as: :text%>
  <%= f.input :capacity, as: :integer%>
  <%= f.input :price_per_day, as: :integer%>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.button :submit , class: "btn-flat"%>
<% end %>

app/views/ships/index.html.erb
 <%= render 'layouts/banner' %>
<div class="subheader-page">
  <h2> Search results</h2>
</div>
<div class="container">
  <div class="cards">
    <%if @ships.any?%>
      <% @ships.each do |ship| %>
        <div class="card-trip">
          <%= link_to "", ship_path(ship), class: 'card-link' %>
          <h2 class="card-trip-pricing">$<%=ship.price_per_day.to_i%></h2>
          <%= ship.picture_1.present? ? image_tag(ship.picture_1) : cl_image_tag(ship.photos[0].blob.key, height: 200, width: 300, crop: :fill) %>
          <div class="card-trip-infos">
            <div class="card-trip-header">
              <h2><%= ship.name %></h2>
              <div class="d-flex">
                <% ship.rating.round.times do %>
                  <i class="fa-solid fa-star"></i>
                <% end %>
                <% (5 - ship.rating.round).times do %>
                  <i class="fa-regular fa-star"></i>
                <% end %>
              </div>
            </div>
            <p><%= truncate(ship.description, length:100) %></p>
          </div>
        </div>
      <% end %>
    <% else %>
      <em>Sorry, no ships found.</em>
    <% end %>
  </div>
</div>

app/views/ships/new.html.erb
<div class="container">
  <h1 class="login-page-header">Add a Spaceship to your Hangar</h1>
  <div class="col-6">
    <%= simple_form_for [@ship] do |f| %>
      <%= f.input :name, as: :string%>
      <%= f.input :description, as: :text%>
      <%= f.input :capacity, as: :integer%>
      <%= f.input :price_per_day, as: :integer%>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
     <%= f.button :submit , class: "btn-flat "%>
    <% end %>
  </div>
</div>

app/views/ships/show.html.erb
<div class="container">
  <br>
  <div style="font-size:40px"><center>
      <h1 class="show-page-header"><strong><%= @ship.name%></strong></h1>
  </div>

 <% if @ship.picture_1.present?%>
      <div class="big-display">
        <div class="card-category" style="width: 300px; height: 200px; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%=@ship.picture_1%>)"></div>
        <div class="card-category" style="width: 300px; height: 200px; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%=@ship.picture_2%>)"></div>
        <div class="card-category" style="width: 300px; height: 200px; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%=@ship.picture_3%>)"></div>
      </div>
    <%else%>
      <div class="big-display">
        <% @ship.photos.each do |picture| %>
          <% photo = picture.record %>
          <div class="card-category" style="width: 300px; height: 200px; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))">
            <%= cl_image_tag picture.blob.key, height: 200, width: 300, crop: :fill %>
          </div>
        <%end%>
      </div>
    <% end %>

  <div class="d-flex">
    <div class="box col-8">
      <div class="description-widget">
        <h4>Description</h4>
          <p><%= @ship.description%></p>
      </div>
    </div>
    <div class="d-flex gap-4 row widget" data-controller="booking-price" data-booking-price-day-value="<%= @ship.price_per_day %>">
      <div class="mb-2">
        <h4 style="text-align: center; font-size: 24px; font-weight: 600; color: #14213d" class="pb-4" >Reservation Summary</h4>
        <div class="d-flex justify-content-between">
          <p class="booking-form-text"> Rating:</p>
          <p class="booking-form-text"><% @ship.rating.round.times do %>
            <i class="fa-solid fa-star"></i>
          <% end %>
          <% (5 - @ship.rating.round).times do %>
            <i class="fa-regular fa-star"></i>
          <% end %>
          </p>
        </div>
        <div class="d-flex justify-content-between">
          <p class="booking-form-text"> Capacity:</p>
          <p class="booking-form-text"><strong><%= @ship.capacity %> Humanoids</strong></p>
        </div>
        <div class="d-flex justify-content-between">
          <p class="booking-form-text"> Price per day:</p>
          <p class="booking-form-text"><strong>$ <%= @ship.price_per_day %></strong></p>
        </div>
      </div>
      <div>
        <%= simple_form_for [@ship, @booking] do |f| %>
          <%= f.input :start_date, as: :string, default: Date.today, input_html: { data: { controller: "datepicker", booking_price_target: "start" , action: "change->booking-price#pricing"  } }, label_html: {class:"booking-form-text"}%>
          <%= f.input :end_date, as: :string, default: Date.today, input_html: { data: { controller: "datepicker", booking_price_target: "end" , action: "change->booking-price#pricing" } }, label_html: {class:"booking-form-text"}%>
          <div class= "booking-form-text text-bold">Total price: $<span data-booking-price-target="total">0.00</span>
          </div>
          <%= f.submit 'Book', class: 'btn-flat-nav mt-3', style: "width:100%"  %>
        <% end %>
      </div>
    </div>
  </div>

</div>